# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plp/proto/Transcription.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='plp/proto/Transcription.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dplp/proto/Transcription.proto\"1\n\x14TranscriptionRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x61udio\x18\n \x01(\x0c\"1\n\x15TranscriptionResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\n \x01(\t2Y\n\x14TranscriptionService\x12\x41\n\x0eTranscribeFile\x12\x15.TranscriptionRequest\x1a\x16.TranscriptionResponse\"\x00\x62\x06proto3'
)




_TRANSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='TranscriptionRequest',
  full_name='TranscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TranscriptionRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio', full_name='TranscriptionRequest.audio', index=1,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=82,
)


_TRANSCRIPTIONRESPONSE = _descriptor.Descriptor(
  name='TranscriptionResponse',
  full_name='TranscriptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TranscriptionResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='TranscriptionResponse.text', index=1,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['TranscriptionRequest'] = _TRANSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['TranscriptionResponse'] = _TRANSCRIPTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TranscriptionRequest = _reflection.GeneratedProtocolMessageType('TranscriptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSCRIPTIONREQUEST,
  '__module__' : 'plp.proto.Transcription_pb2'
  # @@protoc_insertion_point(class_scope:TranscriptionRequest)
  })
_sym_db.RegisterMessage(TranscriptionRequest)

TranscriptionResponse = _reflection.GeneratedProtocolMessageType('TranscriptionResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSCRIPTIONRESPONSE,
  '__module__' : 'plp.proto.Transcription_pb2'
  # @@protoc_insertion_point(class_scope:TranscriptionResponse)
  })
_sym_db.RegisterMessage(TranscriptionResponse)



_TRANSCRIPTIONSERVICE = _descriptor.ServiceDescriptor(
  name='TranscriptionService',
  full_name='TranscriptionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=135,
  serialized_end=224,
  methods=[
  _descriptor.MethodDescriptor(
    name='TranscribeFile',
    full_name='TranscriptionService.TranscribeFile',
    index=0,
    containing_service=None,
    input_type=_TRANSCRIPTIONREQUEST,
    output_type=_TRANSCRIPTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSCRIPTIONSERVICE)

DESCRIPTOR.services_by_name['TranscriptionService'] = _TRANSCRIPTIONSERVICE

# @@protoc_insertion_point(module_scope)
