# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from plp.proto import Transcription_pb2 as plp_dot_proto_dot_Transcription__pb2


class TranscriptionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeFile = channel.unary_unary(
                '/TranscriptionService/TranscribeFile',
                request_serializer=plp_dot_proto_dot_Transcription__pb2.TranscriptionRequest.SerializeToString,
                response_deserializer=plp_dot_proto_dot_Transcription__pb2.TranscriptionResponse.FromString,
                )


class TranscriptionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranscribeFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeFile,
                    request_deserializer=plp_dot_proto_dot_Transcription__pb2.TranscriptionRequest.FromString,
                    response_serializer=plp_dot_proto_dot_Transcription__pb2.TranscriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TranscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TranscriptionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranscribeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TranscriptionService/TranscribeFile',
            plp_dot_proto_dot_Transcription__pb2.TranscriptionRequest.SerializeToString,
            plp_dot_proto_dot_Transcription__pb2.TranscriptionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
